/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _CICDSample;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {
    	System.out.println("Hellow CICD Application");
    }
}
